# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/emiraga/gh/emiraga/wikigraph/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/emiraga/gh/emiraga/wikigraph

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/emiraga/gh/emiraga/wikigraph/CMakeFiles /home/emiraga/gh/emiraga/wikigraph/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/emiraga/gh/emiraga/wikigraph/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

gmock/gmock-gtest-all.o: gmock/gmock-gtest-all.cc.o
.PHONY : gmock/gmock-gtest-all.o

# target to build an object file
gmock/gmock-gtest-all.cc.o:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/gmock/gmock-gtest-all.cc.o
.PHONY : gmock/gmock-gtest-all.cc.o

gmock/gmock-gtest-all.i: gmock/gmock-gtest-all.cc.i
.PHONY : gmock/gmock-gtest-all.i

# target to preprocess a source file
gmock/gmock-gtest-all.cc.i:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/gmock/gmock-gtest-all.cc.i
.PHONY : gmock/gmock-gtest-all.cc.i

gmock/gmock-gtest-all.s: gmock/gmock-gtest-all.cc.s
.PHONY : gmock/gmock-gtest-all.s

# target to generate assembly for a file
gmock/gmock-gtest-all.cc.s:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/gmock/gmock-gtest-all.cc.s
.PHONY : gmock/gmock-gtest-all.cc.s

tests/run_tests.o: tests/run_tests.cc.o
.PHONY : tests/run_tests.o

# target to build an object file
tests/run_tests.cc.o:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/run_tests.cc.o
.PHONY : tests/run_tests.cc.o

tests/run_tests.i: tests/run_tests.cc.i
.PHONY : tests/run_tests.i

# target to preprocess a source file
tests/run_tests.cc.i:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/run_tests.cc.i
.PHONY : tests/run_tests.cc.i

tests/run_tests.s: tests/run_tests.cc.s
.PHONY : tests/run_tests.s

# target to generate assembly for a file
tests/run_tests.cc.s:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/run_tests.cc.s
.PHONY : tests/run_tests.cc.s

tests/test_graph.o: tests/test_graph.cc.o
.PHONY : tests/test_graph.o

# target to build an object file
tests/test_graph.cc.o:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/test_graph.cc.o
.PHONY : tests/test_graph.cc.o

tests/test_graph.i: tests/test_graph.cc.i
.PHONY : tests/test_graph.i

# target to preprocess a source file
tests/test_graph.cc.i:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/test_graph.cc.i
.PHONY : tests/test_graph.cc.i

tests/test_graph.s: tests/test_graph.cc.s
.PHONY : tests/test_graph.s

# target to generate assembly for a file
tests/test_graph.cc.s:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/test_graph.cc.s
.PHONY : tests/test_graph.cc.s

tests/test_writerlib.o: tests/test_writerlib.cc.o
.PHONY : tests/test_writerlib.o

# target to build an object file
tests/test_writerlib.cc.o:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/test_writerlib.cc.o
.PHONY : tests/test_writerlib.cc.o

tests/test_writerlib.i: tests/test_writerlib.cc.i
.PHONY : tests/test_writerlib.i

# target to preprocess a source file
tests/test_writerlib.cc.i:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/test_writerlib.cc.i
.PHONY : tests/test_writerlib.cc.i

tests/test_writerlib.s: tests/test_writerlib.cc.s
.PHONY : tests/test_writerlib.s

# target to generate assembly for a file
tests/test_writerlib.cc.s:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/test_writerlib.cc.s
.PHONY : tests/test_writerlib.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run_tests"
	@echo "... gmock/gmock-gtest-all.o"
	@echo "... gmock/gmock-gtest-all.i"
	@echo "... gmock/gmock-gtest-all.s"
	@echo "... tests/run_tests.o"
	@echo "... tests/run_tests.i"
	@echo "... tests/run_tests.s"
	@echo "... tests/test_graph.o"
	@echo "... tests/test_graph.i"
	@echo "... tests/test_graph.s"
	@echo "... tests/test_writerlib.o"
	@echo "... tests/test_writerlib.i"
	@echo "... tests/test_writerlib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

