#!/bin/sh

rm -v -f Names.php
wget http://svn.wikimedia.org/svnroot/mediawiki/trunk/phase3/languages/Names.php
out=langcodes.py
echo '# autogenerated by info/getlangcodes.sh' > $out
echo 'list = [' >> $out
cut -s -d "'" -f 2 < Names.php | sed "s/^/'/;s/$/'/" | tr '\n' ',' >> $out
echo ']' >> $out

